[package]
name = "csgo-matchbot"
version = "0.1.0"
authors = ["MartinWienc <32913968+MartinWienc@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
reqwest = { version = "0.11.3", features = ["json", "blocking"] }
serenity = { version = "0.11.2", default-features = false, features = ['builder', 'cache', 'client', 'framework', 'gateway', 'http', 'model', 'standard_framework', 'utils', 'rustls_backend', 'unstable_discord_api', 'collector'] }
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
async-std = "1.6.3"
rand = "0.8.5"
regex = "1.3.9"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.4", features = ["postgres", "chrono"] }
diesel-enum = "0.0.5"
dotenv = "0.15.0"
r2d2 = "0.8.10"
r2d2-diesel = "1.0.0"
urlencoding = "2.1.0"
log = "0.4.17"
env_logger = "0.9.0"